### ISSUE TITLE
Error in setup-java.sh file 

### ISSUE THREAD

**Issue by raj19084** [martinprobson/vagrant-hadoop-hive-spark#27]
![Screenshot (830)](https://user-images.githubusercontent.com/58364820/154110542-26f9ddb1-ca45-4ad5-9a69-7ce30d881de1.png)
I am not able to understand why i am getting this error while running vagrant up --provider=virtualbox. Can you help.

**Comment by martinprobson** [comment]
Hello @raj19084 , 
Thanks for pointing this out. The download URL for the mysql connector has changed, hence the curl error.
I have corrected the URL in the `spark-2.3.0` branch of this repo, see [this commit](https://github.com/martinprobson/vagrant-hadoop-hive-spark/pull/28/commits/a04ee9ec06e891dd79d02bfc791884411fac7087).
If you are using another branch you can change the location manually in 
`scripts/common.sh` :-

```
# Old
#JAVA_MYSQL_CONNECTOR_DOWNLOAD=http://central.maven.org/maven2/mysql/mysql-connector-java/${JAVA_MYSQL_CONNECTOR_VERSION}/mysql-connector-java-${JAVA_MYSQL_CONNECTOR_VERSION}.jar
# New
JAVA_MYSQL_CONNECTOR_DOWNLOAD=https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/${JAVA_MYSQL_CONNECTOR_VERSION}/mysql-connector-java-${JAVA_MYSQL_CONNECTOR_VERSION}.jar
```

**Comment by raj19084** [comment]
![Screenshot (831)](https://user-images.githubusercontent.com/58364820/154154694-0e280af3-3942-444d-8036-eecf505f098c.png)

**Comment by raj19084** [comment]
Dear Sir, I am still getting the same error ,I edited the common.sh file manually and also ran vagrant destroy (to delete data related to previous node) and then ran vagrant up command but still got same error.

**Comment by martinprobson** [comment]
Hello @raj19084  That's strange. Could you please try switching to the Spark-2.3.0 branch, and do a vagrant destroy / vagrant up again?
This branch is working fine for me, so would like to check if it works for you.
